USE master
GO
USE DBQuanLyBanHang
GO
CREATE TABLE SANPHAM(
MASP VARCHAR(20) NOT NULL PRIMARY KEY,
TENSP NVARCHAR(100) NOT NULL,
DVTINH NVARCHAR(50),
GIA MONEY
)
GO
CREATE TABLE NHACC(
MANCC VARCHAR(20) NOT NULL PRIMARY KEY,
TENNCC NVARCHAR(100) NOT NULL,
DIACHI NVARCHAR(200) NOT NULL,
PHONE NVARCHAR(20)
)
GO
CREATE TABLE DONHANG(
MADH VARCHAR(20) NOT NULL PRIMARY KEY,
NGAYDH DATE,
MANCC VARCHAR(20) NOT NULL,
FOREIGN KEY(MANCC) REFERENCES dbo.NHACC(MANCC)
)
GO
CREATE TABLE CHITIETDH(
MADH VARCHAR(20) NOT NULL,
MASP VARCHAR(20) NOT NULL,
SLDAT INT,
PRIMARY KEY(MADH,MASP),
FOREIGN KEY(MADH) REFERENCES dbo.DONHANG(MADH),
FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP)
)
GO
CREATE TABLE PHIEUNHAP(
MAPHIEUNHAP VARCHAR(20) NOT NULL PRIMARY KEY,
NGAYNHAP DATE,
MADH VARCHAR(20) NOT NULL,
FOREIGN KEY(MADH) REFERENCES dbo.DONHANG(MADH)
)
GO
CREATE TABLE CHITIETPHIEUNHAP(
MAPHIEUNHAP VARCHAR(20) NOT NULL,
MASP VARCHAR(20) NOT NULL,
SLNHAP INT,
DONGIANHAP MONEY,
PRIMARY KEY(MAPHIEUNHAP,MASP),
FOREIGN KEY(MAPHIEUNHAP) REFERENCES dbo.PHIEUNHAP(MAPHIEUNHAP),
FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP)
)
GO
CREATE TABLE PHIEUXUAT(
MAPHIEUXUAT VARCHAR(20) NOT NULL PRIMARY KEY,
NGAYXUAT DATE,
TENKH NVARCHAR(100)
)
GO
CREATE TABLE CHITIETPHIEUXUAT(
MAPHIEUXUAT VARCHAR(20) NOT NULL,
MASP VARCHAR(20) NOT NULL,
SLXUAT INT,
DONGIAXUAT MONEY,
PRIMARY KEY(MAPHIEUXUAT,MASP),
FOREIGN KEY(MAPHIEUXUAT) REFERENCES dbo.PHIEUXUAT(MAPHIEUXUAT),
FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP)
)
GO
CREATE TABLE TONKHO(
MATON VARCHAR(20) NOT NULL,
MASP VARCHAR(20) NOT NULL,
SLDAU INT,
TONGSLNHAP INT,
TONGSLXUAT INT,
SLCUOI INT,
PRIMARY KEY(MATON,MASP),
FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP)
)
GO
SELECT * FROM dbo.DONHANG
GO 
SELECT * FROM dbo.CHITIETDH
SELECT CHITIETDH.MADH, NGAYDH,MANCC,MASP,SLDAT FROM dbo.DONHANG INNER JOIN dbo.CHITIETDH ON CHITIETDH.MADH = DONHANG.MADH
GO
CREATE PROCEDURE CHITIET_DONHANG
AS
BEGIN
	SELECT CHITIETDH.MADH, NGAYDH,MANCC,MASP,SLDAT FROM dbo.DONHANG INNER JOIN dbo.CHITIETDH ON CHITIETDH.MADH = DONHANG.MADH
END
GO
	SELECT CHITIETPHIEUNHAP.MAPHIEUNHAP, NGAYNHAP, MADH,MASP,SLNHAP,DONGIANHAP
	 FROM dbo.PHIEUNHAP INNER JOIN dbo.CHITIETPHIEUNHAP
	  ON CHITIETPHIEUNHAP.MAPHIEUNHAP = PHIEUNHAP.MAPHIEUNHAP
GO
CREATE PROCEDURE PROC_CHITIET_PHIEUNHAP
AS
BEGIN
	SELECT CHITIETPHIEUNHAP.MAPHIEUNHAP, NGAYNHAP, MADH,MASP,SLNHAP,DONGIANHAP
	 FROM dbo.PHIEUNHAP INNER JOIN dbo.CHITIETPHIEUNHAP
	  ON CHITIETPHIEUNHAP.MAPHIEUNHAP = PHIEUNHAP.MAPHIEUNHAP
END

GO
SELECT MASP FROM dbo.PHIEUNHAP INNER JOIN dbo.DONHANG
	ON DONHANG.MADH = PHIEUNHAP.MADH
	INNER JOIN dbo.CHITIETDH
	ON CHITIETDH.MADH = DONHANG.MADH
	WHERE MAPHIEUNHAP='phieu2'
GO


SELECT dbo.SANPHAM.MASP,TENSP,DVTINH,GIA FROM dbo.PHIEUNHAP INNER JOIN dbo.DONHANG
	ON DONHANG.MADH = PHIEUNHAP.MADH
	INNER JOIN dbo.CHITIETDH
	ON CHITIETDH.MADH = DONHANG.MADH
	INNER JOIN dbo.SANPHAM
	ON SANPHAM.MASP = CHITIETDH.MASP
	WHERE MAPHIEUNHAP='phieu2'

GO
ALTER PROCEDURE PROC_SANPHAMTHEOPHIEU(@MAPHIEU VARCHAR(20))
AS
BEGIN
	SELECT dbo.SANPHAM.MASP,TENSP,DVTINH,SANPHAM.SOLUONG FROM dbo.PHIEUNHAP INNER JOIN dbo.DONHANG
	ON DONHANG.MADH = PHIEUNHAP.MADH
	INNER JOIN dbo.CHITIETDH
	ON CHITIETDH.MADH = DONHANG.MADH
	INNER JOIN dbo.SANPHAM
	ON SANPHAM.MASP = CHITIETDH.MASP
	WHERE MAPHIEUNHAP=@MAPHIEU
END
GO
ALTER TRIGGER TRG_PHIEUNHAP
ON dbo.CHITIETPHIEUNHAP
FOR INSERT
AS
BEGIN
	DECLARE @SLDAT INT
	DECLARE @SLNHAP INT
	DECLARE @maDH VARCHAR(20)
	SELECT @maDH= MADH FROM dbo.PHIEUNHAP INNER JOIN Inserted ON Inserted.MAPHIEUNHAP = PHIEUNHAP.MAPHIEUNHAP WHERE Inserted.MAPHIEUNHAP=Inserted.MAPHIEUNHAP
	SELECT @SLDAT= SLDAT FROM dbo.CHITIETDH INNER JOIN dbo.SANPHAM ON SANPHAM.MASP = CHITIETDH.MASP
	INNER JOIN Inserted ON Inserted.MASP = SANPHAM.MASP
	SELECT @SLNHAP= Inserted.SLNHAP FROM Inserted
	IF(@SLNHAP>@SLDAT)
		BEGIN
			RAISERROR('KHONG DU HANG',16,1)
			ROLLBACK TRANSACTION
		END
	ELSE
		BEGIN
			UPDATE dbo.CHITIETDH SET SLDAT=SLDAT-@SLNHAP FROM dbo.CHITIETDH INNER JOIN dbo.SANPHAM
			ON SANPHAM.MASP = CHITIETDH.MASP INNER JOIN Inserted
			ON Inserted.MASP = SANPHAM.MASP WHERE MADH= @maDH

			UPDATE dbo.SANPHAM SET SOLUONG=SOLUONG+@SLNHAP FROM dbo.SANPHAM INNER JOIN Inserted ON Inserted.MASP = SANPHAM.MASP 
		END
END
GO
SELECT * FROM dbo.CHITIETPHIEUNHAP
GO
SELECT * FROM dbo.PHIEUNHAP

GO
CREATE TRIGGER TRG_XUATHANG
ON dbo.CHITIETPHIEUXUAT
FOR INSERT
AS
BEGIN
	DECLARE @SLHANG INT
	DECLARE @SLXUAT INT
	DECLARE @MASP VARCHAR(20)
	SELECT @SLHANG = SOLUONG FROM dbo.SANPHAM INNER JOIN Inserted
				ON Inserted.MASP = SANPHAM.MASP
	SELECT @SLXUAT = Inserted.SLXUAT FROM Inserted
	SELECT @MASP= Inserted.MASP FROM Inserted
	IF(@SLXUAT>@SLHANG)
		BEGIN
			RAISERROR('KHONG DU HANG',16,1)
			ROLLBACK TRANSACTION
		END
	ELSE
	BEGIN
		UPDATE dbo.SANPHAM SET SOLUONG=SOLUONG-@SLXUAT WHERE MASP=@MASP 
	END
END
GO
ALTER PROCEDURE PROC_CHITIETPHIEUXUAT
AS
BEGIN
	SELECT CHITIETPHIEUXUAT.MAPHIEUXUAT,NGAYXUAT,TENKH,MASP,SLXUAT,DONGIAXUAT FROM dbo.PHIEUXUAT INNER JOIN dbo.CHITIETPHIEUXUAT
	ON CHITIETPHIEUXUAT.MAPHIEUXUAT = PHIEUXUAT.MAPHIEUXUAT
END
GO
SELECT * FROM dbo.CHITIETPHIEUNHAP
GO
SELECT SUM(SLNHAP) AS 'SOLUONG' FROM dbo.CHITIETPHIEUNHAP WHERE MASP='sp1'
SELECT * FROM dbo.CHITIETPHIEUXUAT
GO
CREATE PROCEDURE PROC_SLNHAP(@MASP VARCHAR(20))
AS
BEGIN
	SELECT SUM(SLNHAP) AS 'SOLUONG' FROM dbo.CHITIETPHIEUNHAP WHERE MASP=@MASP
END

GO
CREATE PROCEDURE PROC_SLXUAT(@MASP VARCHAR(20))
AS
BEGIN
	SELECT SUM(SLXUAT) AS 'SOLUONG' FROM dbo.CHITIETPHIEUXUAT WHERE MASP=@MASP
END

GO
CREATE PROCEDURE PROC_TONGTIENNHAP(@NGAY1 DATE, @NGAY2 DATE)
AS
BEGIN
	SELECT SUM(THANHTIEN) AS 'TONGTHANHTIEN' FROM dbo.PHIEUNHAP INNER JOIN dbo.CHITIETPHIEUNHAP 
	ON CHITIETPHIEUNHAP.MAPHIEUNHAP = PHIEUNHAP.MAPHIEUNHAP
	WHERE dbo.PHIEUNHAP.NGAYNHAP BETWEEN '2020-06-24' AND '2020-06-24' 
END
GO
CREATE PROCEDURE PROC_TONGTIENXUAT(@NGAY1 DATE, @NGAY2 DATE)
AS
BEGIN
	SELECT SUM(THANHTIEN) AS 'TONGTHANHTIEN' FROM dbo.CHITIETPHIEUXUAT INNER JOIN dbo.PHIEUXUAT
	ON PHIEUXUAT.MAPHIEUXUAT = CHITIETPHIEUXUAT.MAPHIEUXUAT
	WHERE NGAYXUAT BETWEEN '' AND ''
END
